# Generated by Django 2.1.3 on 2018-11-16 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('timeDateDispatched', models.DateTimeField()),
                ('alarmLevel', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('codeName', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='incident',
            name='dispatchedUnits',
            field=models.ManyToManyField(to='firestation_etl.Units'),
        ),
        migrations.AddField(
            model_name='incident',
            name='incidentType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firestation_etl.IncidentType'),
        ),
        migrations.AddField(
            model_name='incident',
            name='nearestStation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='firestation_etl.Station'),
        ),
    ]
